<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>
<?php use_helper('sfExtjs2'); //(Probably OBSOLETE, I don't think this is necessary anymore) ?>  

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($bd->getId()): ?>
Modification de BD
<?php else: ?>
Saisie de BD
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	

<div id="corps">	
<ul id="actions" class="x-hidden">
	<li>
		<a id="use" href="#">Use Existing Tab</a>
	</li>
	<li>
		<a id="create" href="#">Create New Tab</a>
	</li>
</ul>
<div id="tabs"></div></div>
	
<div id="msg" style="visibility: hidden"></div>
Name: <input type="text" id="name"><br>
<input type="button" id="myButton" value="OK">

<?php
  $sfExtjs2Plugin = new sfExtjs2Plugin(array('theme'=>'gray'), array('css' => '/sfExtjsThemePlugin/css/symfony-extjs.css'));
$tab1info = "Tab content to go here e.g. a welcome page";
$tab2info = "Tab content to go here e.g. a data grid";

$sfExtjs2Plugin->load();
$sfExtjs2Plugin->begin();

// **************************************
// Application
// **************************************

/*$sfExtjs2Plugin_App_viewport = $sfExtjs2Plugin->Viewport(array
(
  'layout' => 'border',  'applyTo' => 'corps', 'items'  => array
  (
  	$sfExtjs2Plugin->Panel(array
  	(
    	'id'=>'action-panel',
    	'region' =>'west',
    	'split' => 'true',
          	'collapsible'=>'true',
          	'collapseMode'=>'mini',
  	'width'=>'200',
  	'minWidth'=>'150',
          	'border'=>'false',
          	'baseCls'=>'x-plain',
          	'items' => array($sfExtjs2Plugin->Panel(array
  	(
    	'id'=>'tabActions',
  	'frame'=>'true',
    	'title'=>'Actions',
          	'collapsible'=>'true',
          	'contentEl'=>'actions',
          	'titleCollapse'=>'true'
    ))))
    ) ,
    $sfExtjs2Plugin->TabPanel(array
    (
      'id'=>'tonyCp',
      'region'=>'center',
      'deferredRender'=>'false',
        'autoScroll'=>'true',
    'margins'=>'0 4 4 0',
    'activeTab'=>'0',
    'items'=>array(
        $sfExtjs2Plugin->Panel(array(
          'id'=>'tab1',
          'contentEl'=>'tabs',
        'title'=>'BD',
        'closable'=>'false',
        'autoScroll'=>'true'
        ))
      )
    ))
  )
));

$sfExtjs2Plugin->beginApplication(array
(
  'name'   => 'App',
  'public' => array(
  'init' => $sfExtjs2Plugin->asMethod("$sfExtjs2Plugin_App_viewport;")
)
));

$sfExtjs2Plugin->endApplication();
$sfExtjs2Plugin->end('Ext.onReady(App.init, App);');*/


$sfExtjs2Plugin->beginApplication(array
(
  'name'   => 'App',
  'public' => array(
    'init' => $sfExtjs2Plugin->asMethod("alert('Congratulations! You have Ext configured correctly!')")))
  );
$sfExtjs2Plugin->endApplication();
  
//$sfExtjs2Plugin->end('Ext.onReady(App.init, App);');
  
$sfExtjs2Plugin->end(
"Ext.onReady(function() {
	Ext.get('myButton').on('click', function(){
		var msg = Ext.get('msg');
		msg.load({
			url: ['http://localhost:81/frontend_dev.php/gereBD/TestUpdate'], 
			params: 'name=' + Ext.get('Name').dom.value,
			text: 'Updating...'
		});
		msg.show();
	})});"
);


?>
