<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>
<?php use_helper('sfExtjs2'); 
$sfExtjs2Plugin = new sfExtjs2Plugin(array('theme'=>'gray'), array('css' => '/sfExtjsThemePlugin/css/symfony-extjs.css'));
?>
<?php
  $sfExtjs2Plugin->load();
  $sfExtjs2Plugin->begin();
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($bd->getId()): ?>
Modification de BD
<?php else: ?>
Saisie de BD
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	


<?php echo form_tag('gereBD/update?sort='.$sf_request->getParameter('sort'), array('name' => 'formEditBd')) ?>
<?php echo object_input_hidden_tag($bd, 'getId') ?>
<table>
<tbody>
<tr><td><?php echo form_error('serie') ?></td></tr>
<tr><td>Serie :</td><td><div id='txNomSerie'><?php
    echo input_hidden_tag('id_nomSerie', '');
    echo input_auto_complete_tag('nomSerie',
               '',
               'gereBD/autoCompleteNomSerie',
               array('autocomplete' => 'on'),
               array('use_style' => true));
?>
</div></td><td>
<?php echo ' '.link_to('Rechercher Série',  'gereBD/rechercheSerie', 'popup=true') ?></td></tr>
<tr><td><?php echo form_error('talbum') ?></td></tr>
<tr><td>Titre :</td><td>				 <?php echo object_input_tag($bd, 'getTalbum', array ('size' => 50,)) ?></td></tr>
<tr><td><?php echo form_error('editeur') ?></td></tr>
<tr><td>Editeur :</td><td><div id='txNomEditeur'><?php
    echo input_hidden_tag('id_nomEditeur', '');
    echo input_auto_complete_tag('nomEditeur',
               '',
               'gereBD/autoCompleteNomEditeur',
               array('autocomplete' => 'on'),
               array('use_style' => true));
?>
</div></td><td>
<?php echo ' '.link_to('Rechercher Editeur',  'gereBD/rechercheEditeur', 'popup=true') ?></td></tr>
<tr><td><?php echo form_error('genre') ?></td></tr>
<tr><td>Genre :</td><td><div id='txNomGenre'><?php
    echo input_hidden_tag('id_nomGenre', '');
    echo input_auto_complete_tag('nomGenre',
               '',
               'gereBD/autoCompleteNomGenre',
               array('autocomplete' => 'on'),
               array('use_style' => true));
?>
</div></td><td>
<?php echo ' '.link_to('Rechercher Genre',  'gereBD/rechercheGenre', 'popup=true') ?></td></tr>
<tr><td><?php echo form_error('dateParu') ?></td></tr>
<tr><td>Date parution:</td><td>       <?php echo object_input_tag($bd, 'getDateParu', array ('rich' => true,)) ?></td></tr>
<tr><td><?php echo form_error('histoire') ?></td></tr>
<tr><td>Résumé:</td><td>             <?php echo object_textarea_tag($bd, 'getHistoire', array ('rich' => true,)) ?></td>
<tr><td><?php echo form_error('commentaire') ?></td></tr>
<tr><td>Commentaire:</td><td>             <?php echo object_textarea_tag($bd, 'getCommentaire', array ('rich' => true,)) ?></td></tr>
<tr><td><?php echo form_error('depotLegal') ?></td></tr>
<tr><td>Date dépôt légal:</td><td>       <?php echo object_input_tag($bd, 'getDepotLegal', array ('rich' => true,)) ?></td></tr>
<tr><td><?php echo form_error('ISBN') ?></td></tr>
<tr><td>ISBN:</td><td>          <?php echo object_input_tag($bd, 'getISBN', array ('size' => 20,)) ?></td></tr>
<tr><td><?php echo form_error('ISSN') ?></td></tr>
<tr><td>ISSN:</td><td>          <?php echo object_input_tag($bd, 'getISSN', array ('size' => 20,)) ?></td></tr>
<tr><td><?php echo form_error('nbrePage') ?></td></tr>
<tr><td>Nombre de pages:</td><td>             <?php echo object_input_tag($bd, 'getNbrePage', array ('size' => 3,)) ?></td></tr>
<tr><td><?php echo form_error('photo1') ?></td></tr>
<tr><td>Photo 1:</td><td>             <?php echo image_tag($bd->getPhoto1()).' '.input_file_tag('photo1') ?></td></tr>
<tr><td><?php echo form_error('photo2') ?></td></tr>
<tr><td>Photo 2:</td><td>             <?php echo image_tag($bd->getPhoto2()).' '.input_file_tag('photo2') ?></td></tr>

</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
</form>
<?php if ($bd->getId()): ?>
  &nbsp;<?php echo link_to(image_tag('bt_supprimer', array('border' => 0)), 'gereBD/delete?id='.$bd->getId().'&sort='.$sf_request->getParameter('sort'), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereBD/list?sort='.$sf_request->getParameter('sort')) ?>
<?php else: ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereBD/list?sort='.$sf_request->getParameter('sort')) ?>
<?php endif; ?>