<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>

<table cellspacing=0 cellpadding=0>
<tr>
<td>
<?php echo image_tag('bord_gauche_titre_liste.gif', array('border' => 0)) ?>
</td>
<td class="titrePageList">
Recherche de BD
</td>
<td>
<?php echo image_tag('bord_droite_titre_liste.gif', array('border' => 0,'background-position' => 'left')) ?>
</td>
</tr>
<tr>
<?php echo $pager->getNbResults() ?> résultats trouvés.<br/>
Affichage des résultats <?php echo $pager->getFirstIndice() ?> à  <?php echo $pager->getLastIndice() ?>.
</tr>
</table>



<table>
<thead class="listeObjetTitreTableau">
<tr>
  <th><?php echo link_to ('Collection', 'gereBD/recherche?sort=Collection') ?></th>
  <th><?php echo link_to ('Titre', 'gereBD/recherche?sort=Titre') ?></th>
  <th><?php echo link_to ('Année', 'gereBD/recherche?sort=Dtedition') ?></th>
  <th><?php echo link_to ('Auteur', 'gereBD/recherche?sort=Dessinateurnom') ?></th>
  <th>Action</th>
</tr>
</thead>
<tbody class="listeObjetLigneTableau">
<?php foreach ($pager->getResults() as $obj): ?>
<tr>
      <td><?php echo $obj->getBd()->getCollection() ?></td>
      <td><?php echo $obj->getBd()->getTitre() ?></td>
      <td><?php echo $obj->getBd()->getDtedition() ?></td>
      <td><?php echo $obj->getBd()->getDessinateurnom()." ".$obj->getBd()->getDessinateurprenom()?></td>
      <td>
		<u><?php echo link_to (image_tag('bt_voir', array('border' => 0)), 'gereBD/show?id='.$obj->getBd()->getId().'&sort='.$sf_request->getParameter('sort'))?></u>
      <?php if($sf_user->getAttribute('id')== $obj->getUtilisateurId()) : ?>
		<u><?php echo link_to ('Vitrine', 'gereBD/maVitrine?utilid='.$obj->getUtilisateurId())?></u>
      <?php else: ?>
		<u><?php echo link_to ('Vitrine', 'gereBD/saVitrine?utilid='.$obj->getUtilisateurId().'&login='.$obj->getUtilisateur()->getLogin())?></u>
	      <?php if($sf_user->hasCredential('troqueur')): ?>
			<u><?php echo link_to ('troquer', 'gereTroc/list?utilid='.$obj->getUtilisateurId())?></u> 
	      <?php endif; ?>
      <?php endif; ?>
      </td>
</tr>
<?php endforeach; ?>
</tbody>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><?php echo $sf_flash->get('messageFin')?></tr>
<?php endif; ?>
</table>
<?php if($sf_user->hasCredential('troqueur')): ?>
   <?php echo link_to (image_tag('bt_ajouterBD', array('border' => 0)), 'gereBD/create?sort='.$sf_request->getParameter('sort'))?>
<?php endif; ?>

<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to('&laquo;', 'gereBD/recherche?page='.$pager->getFirstPage().'&sort='.$sf_request->getParameter('sort')) ?>
  <?php echo link_to('&lt;', 'gereBD/recherche?page='.$pager->getPreviousPage().'&sort='.$sf_request->getParameter('sort')) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, 'gereBD/recherche?page='.$page.'&sort='.$sf_request->getParameter('sort')) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?> - <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('&gt;', 'gereBD/recherche?page='.$pager->getNextPage().'&sort='.$sf_request->getParameter('sort')) ?>
  <?php echo link_to('&raquo;', 'gereBD/recherche?page='.$pager->getLastPage().'&sort='.$sf_request->getParameter('sort')) ?>
<?php endif ?>

