<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>
<?php use_helper('sfExtjs2'); //(Probably OBSOLETE, I don't think this is necessary anymore) ?>  

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($bd->getId()): ?>
Modification de BD
<?php else: ?>
Saisie de BD
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	

<div id="msg" style="visibility: hidden"></div>


<div id="tabs"></div>

<?php
$sfExtjs2Plugin = new sfExtjs2Plugin(array('theme'=>'gray'), array('css' => '/sfExtjsThemePlugin/css/symfony-extjs.css'));
$tab1info = "Tab content to go here e.g. a welcome page";
$tab2info = "Tab content to go here e.g. a data grid";

$sfExtjs2Plugin->load();
$sfExtjs2Plugin->begin();

// **************************************
// Application
// **************************************
$private  = array() ;
$public  = array() ;
    
$tabPanel = $sfExtjs2Plugin->TabPanel(array
    (
      'renderTo' => 'tabs',
      'resizeTabs'=>'true',
      'enableTabScroll'=>'true',
      'autoScroll'=>'true',
      'region'=>'center',
      'margins'=>'0 4 4 0',
      'deferredRender'=>'false'
    ));

/*$tab = $sfExtjs2Plugin->Panel(array(
          	'title'=>'tab1',
        	'html'=>'content',
        	'closable'=>'true'
        ));
*/
     
$button = $sfExtjs2Plugin->Button(array
    (
      'text'=>'Add Tab',
      'renderTo' => 'tabs',
      'handler' => $sfExtjs2Plugin->asVar('addTab')));

$addTab = $sfExtjs2Plugin->asMethod(array('name' => 'addTab', 'source' => '
	   alert("gagné !!!!");
'));

$sfExtjs2Plugin_App_viewport = $sfExtjs2Plugin->Viewport(array
(
  'layout' => 'border',   'items'  => array
  ( $addTab, $sfExtjs2Plugin->asVar($button), $sfExtjs2Plugin->asVar($tabPanel))));
  
$public['init'] = $sfExtjs2Plugin->asMethod("
	Ext.QuickTips.init();  $sfExtjs2Plugin_App_viewport;
");
	
	
$sfExtjs2Plugin->beginApplication(array
(
  'name'   => 'App',
  'private' => $private,
  'public' => $public 
));

$sfExtjs2Plugin->endApplication();
$sfExtjs2Plugin->end('Ext.onReady(App.init, App);');

 
/*$sfExtjs2Plugin->end(
"Ext.onReady(function() {
	Ext.get('myButton').on('click', function(){
		var msg = Ext.get('msg');
		msg.load({
			url: ['http://localhost:81/frontend_dev.php/gereBD/TestUpdate'], 
			params: 'name=' + Ext.get('Name').dom.value,
			text: 'Updating...'
		});
		msg.show();
	})});"
);*/


?>
