<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($serie->getId()): ?>
Modification de Serie
<?php else: ?>
Saisie de Serie
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	
<div id="corps"></div>	
<div id="corps"></div>	

<?php
use_helper('sfExtjs2'); //(Probably OBSOLETE, I don't think this is necessary anymore)
$sfExtjs2Plugin = new sfExtjs2Plugin(array('theme'=>'gray'), array('css' => '/sfExtjsThemePlugin/css/symfony-extjs.css'));

$sfExtjs2Plugin->load();
$sfExtjs2Plugin->begin();

// **************************************
// Application
// **************************************


$sfExtjs2Plugin_App_viewport = $sfExtjs2Plugin->Viewport(array
(
  'name' => 'formEditSerie', 'layout' => 'border', 'applyTo' => 'corps', 'items'  => array
  (
    $sfExtjs2Plugin->FormPanel(array
    (
    'items'=> array(
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'Nom', 'name'=>'nom')), 
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'Histoire', 'name'=>'histoire')),
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'Commentaire', 'name'=>'commentaire')),
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'SiteWeb1', 'name'=>'siteWeb1')),
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'SiteWeb2', 'name'=>'siteWeb2')),
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'Photo1', 'name'=>'photo1')),
    $sfExtjs2Plugin->TextField(array('fieldLabel'=>'Photo2', 'name'=>'photo2')),
    $sfExtjs2Plugin->Button(array('fieldLabel'=>'Enregistrer', 'handler'=> $sfExtjs2Plugin->Function(array('url' => 'gereBD/updateSerie'))))
    )
  )))))
;


$sfExtjs2Plugin->beginApplication(array
(
  'name'   => 'App',
  'public' => array(
    'init' => $sfExtjs2Plugin->asMethod("$sfExtjs2Plugin_App_viewport;"
  )
)
));

$sfExtjs2Plugin->endApplication();
$sfExtjs2Plugin->end('Ext.onReady(App.init, App);');
?>
