<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($bd->getId()): ?>
Modification de BD
<?php else: ?>
Saisie de BD
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	


<?php echo form_tag('gereBD/update?sort='.$sf_request->getParameter('sort'), 'multipart=true' , array('name' => 'formEditBd')) ?>
<?php echo object_input_hidden_tag($bd, 'getId') ?>
<table>
<tbody>
<tr><td><?php echo form_error('serie') ?></td></tr>
<tr><td>Serie :</td><td>
<div id="txNomSerie">
<?php
    echo input_hidden_tag('idNomSerie', $idSerie) ;
    echo input_auto_complete_tag('nomSerie',
               $nomSerie,
               'gereBD/autoCompleteNomSerie',
               array('autocomplete' => 'off'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomSerie').value = selectedItem.id; }"));
?>
</div></td><td>
</td></tr>
<tr><td><?php echo form_error('talbum') ?></td></tr>
<tr><td>Titre :</td><td>				 <?php echo object_input_tag($bd, 'getTalbum', array ('size' => 50,)) ?></td></tr>
<tr><td><?php echo form_error('editeur') ?></td></tr>
<tr><td>Editeur :</td><td><div id='txNomEditeur'><?php
echo input_hidden_tag('idNomEditeur', $idEditeur);
echo input_auto_complete_tag('nomEditeur',
               $nomEditeur,
               'gereBD/autoCompleteNomEditeur',
               array('autocomplete' => 'off'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomEditeur').value = selectedItem.id; }"));
?>
</div></td><td>
</td></tr>
<tr><td><?php echo form_error('genre') ?></td></tr>
<tr><td>Genre :</td><td><div id='txNomGenre'><?php
echo input_hidden_tag('idNomGenre', $idGenre);
echo input_auto_complete_tag('nomGenre',
               $nomGenre,
               'gereBD/autoCompleteNomGenre',
               array('autocomplete' => 'off'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomGenre').value = selectedItem.id; }"));
?>
</div></td><td>
</td></tr>
<tr><td><?php echo form_error('idNomScenariste') ?></td></tr>
<tr><td>Scenariste :</td><td><div id='txNomScenariste'><?php
echo input_hidden_tag('idNomScenariste', $idScenariste);
echo input_auto_complete_tag('nomScenariste',
               $nomScenariste,
               'gereBD/autoCompleteNomScenariste',
               array('autocomplete' => 'off'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomScenariste').value = selectedItem.id; }"));
?>
</div></td><td>
</td></tr>
<tr><td><?php echo form_error('idNomDessinateur') ?></td></tr>
<tr><td>Dessinateur :</td><td><div id='txNomDessinateur'><?php
echo input_hidden_tag('idNomDessinateur', $idDessinateur);
echo input_auto_complete_tag('nomDessinateur',
               $nomDessinateur,
               'gereBD/autoCompleteNomDessinateur',
               array('autocomplete' => 'off'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomDessinateur').value = selectedItem.id; }"));
?>
</div></td><td>
</td></tr>
<tr><td><?php echo form_error('idNomColoriste') ?></td></tr>
<tr><td>Coloriste :</td><td><div id='txNomColoriste'><?php
echo input_hidden_tag('idNomColoriste', $idColoriste);
echo input_auto_complete_tag('nomColoriste',
               $nomColoriste,
               'gereBD/autoCompleteNomColoriste',
               array('autocomplete' => 'off'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomColoriste').value = selectedItem.id; }"));
?>
</div></td><td>
</td></tr>
<tr><td><?php echo form_error('dateParu') ?></td></tr>
<tr><td>Date parution:</td><td>       <?php echo object_input_date_tag($bd, 'getDateparu', array ('rich' => true,'culture' => $sf_user->getCulture(),)) ?></td></tr>
<tr><td><?php echo form_error('histoire') ?></td></tr>
<tr><td>Résumé:</td><td>             <?php echo object_textarea_tag($bd, 'getHistoire', array ('rich' => true,)) ?></td>
<tr><td><?php echo form_error('commentaire') ?></td></tr>
<tr><td>Commentaire:</td><td>             <?php echo object_textarea_tag($bd, 'getCommentaire', array ('rich' => true,)) ?></td></tr>
<tr><td><?php echo form_error('depotLegal') ?></td></tr>
<tr><td>Date dépôt légal:</td><td>       <?php echo object_input_date_tag($bd, 'getDepotlegal', array ('rich' => true,'culture' => $sf_user->getCulture(),)) ?></td></tr>
<tr><td><?php echo form_error('ISBN') ?></td></tr>
<tr><td>ISBN:</td><td>          <?php echo object_input_tag($bd, 'getIsbn', array ('size' => 20,)) ?></td></tr>
<tr><td><?php echo form_error('ISSN') ?></td></tr>
<tr><td>ISSN:</td><td>          <?php echo object_input_tag($bd, 'getIssn', array ('size' => 20,)) ?></td></tr>
<tr><td><?php echo form_error('nbrePage') ?></td></tr>
<tr><td>Nombre de pages:</td><td>             <?php echo object_input_tag($bd, 'getNbrepage', array ('size' => 3,)) ?></td></tr>
<tr><td><?php echo form_error('photo1') ?></td></tr>
<tr><td>Photo 1:</td><td>             <?php echo image_tag(UPLOAD_BD_DIR_REL.'/'.$bd->getPhoto1(),'size=150x200').' '.input_file_tag('photo1') ?></td></tr>
<tr><td><?php echo form_error('photo2') ?></td></tr>
<tr><td>Photo 2:</td><td>             <?php echo image_tag(UPLOAD_BD_DIR_REL.'/'.$bd->getPhoto2(),'size=150x200').' '.input_file_tag('photo2') ?></td></tr>

</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
</form>
<?php if ($bd->getId()): ?>
  &nbsp;<?php echo link_to(image_tag('bt_supprimer', array('border' => 0)), 'gereBD/delete?id='.$bd->getId().'&sort='.$sf_request->getParameter('sort'), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereBD/recherche?sort='.$sf_request->getParameter('sort').'&rechercher='.$rechercher.'&filtrePossede='.$sf_request->getParameter('filtrePossede')) ?>
<?php else: ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereBD/recherche?sort='.$sf_request->getParameter('sort').'&rechercher='.$rechercher.'&filtrePossede='.$sf_request->getParameter('filtrePossede')) ?>
<?php endif; ?>