<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($auteur->getId()): ?>
Modification Auteur
<?php else: ?>
Saisie Auteur
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	


<?php echo form_tag('gereBD/updateAuteur?sort='.$sf_request->getParameter('sort'), array('name' => 'formEditAuteur')) ?>
<?php echo object_input_hidden_tag($auteur, 'getId') ?>
<table>
<tbody>
<tr><td><?php echo form_error('nom') ?></td></tr>
<tr><td>Nom:</td><td><?php echo object_input_tag($auteur, 'getNom') ?></td></tr>
<tr><td><?php echo form_error('prenom') ?></td></tr>
<tr><td>Prénom:</td><td><?php echo object_input_tag($auteur, 'getPrenom') ?></td></tr>
<tr><td><?php echo form_error('surnom') ?></td></tr>
<tr><td>Surnom :</td><td><?php echo object_input_tag($auteur, 'getSurnom') ?></td></tr>
<tr><td><?php echo form_error('dessinateur') ?></td></tr>
<tr><td>Dessinateur:</td><td><?php echo object_checkbox_tag($auteur, 'getDessinateur') ?></td></tr>
<tr><td><?php echo form_error('coloriste') ?></td></tr>
<tr><td>Coloriste:</td><td><?php echo object_checkbox_tag($auteur, 'getColoriste') ?></td></tr>
<tr><td><?php echo form_error('scenariste') ?></td></tr>
<tr><td>Scenariste:</td><td><?php echo object_checkbox_tag($auteur, 'getScenariste') ?></td></tr>
<tr><td><?php echo form_error('dateNaissance') ?></td></tr>
<tr><td>Date de naissance:</td><td>       <?php echo object_input_tag($auteur, 'getDateNaissance', array ('rich' => true,)) ?></td></tr>
<tr><td><?php echo form_error('lieuNaissance') ?></td></tr>
<tr><td>Lieu de naissance:</td><td><?php echo object_input_tag($auteur, 'getLieuNaissance') ?></td></tr>
<tr><td><?php echo form_error('commentaire') ?></td></tr>
<tr><td>Commentaire:</td><td>             <?php echo object_textarea_tag($auteur, 'getCommentaire', array ('rich' => true,)) ?></td></tr>
<tr><td><?php echo form_error('pays') ?></td></tr>
<tr><td>Pays:</td><td><div id='txNomPayx'><?php
echo input_hidden_tag('idNomPays', $idPays);
echo input_auto_complete_tag('nomPays',
               $nomPays,
               'gereBD/autoCompleteNomPays',
               array('autocomplete' => 'on'),
               array('use_style' => true, 'after_update_element' => "function (inputField, selectedItem) { $('idNomPays').value = selectedItem.id; }"));
               ?>
</div></td><td>
<tr><td><?php echo form_error('siteweb1') ?></td></tr>
<tr><td>Site web 1 :</td><td>		 <?php echo object_input_tag($auteur, 'getWeb1') ?></td></tr>
<tr><td><?php echo form_error('siteweb2') ?></td></tr>
<tr><td>Site web 2 :</td><td>		 <?php echo object_input_tag($auteur, 'getWeb2') ?></td></tr>
<tr><td><?php echo form_error('photo1') ?></td></tr>
<tr><td>Photo 1:</td><td>             <?php echo image_tag($auteur->getPhoto1(),'size=150x200').' '.input_file_tag('photo1') ?></td></tr>
<tr><td><?php echo form_error('photo2') ?></td></tr>
<tr><td>Photo 2:</td><td>             <?php echo image_tag($auteur->getPhoto2(),'size=150x200').' '.input_file_tag('photo2') ?></td></tr>
</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
</form>
&nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereBD/rechercheAuteur') ?>
