<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Consultation des Auteurs
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tbody>
<tr><td>Auteur:</td><td><?php echo $auteur->getPrenom().' '.$auteur->getNom() ?></td></tr>
<tr><td></td><td><?php echo $auteur->getSurnom() ?></td></tr>
<tr><td> </td><td><?php echo image_tag($auteur->getPhoto1()) ?></td></tr>
<tr><td> </td><td><?php echo image_tag($auteur->getPhoto2()) ?></td></tr>
<tr><td>Commentaire:</td><td><?php echo html_entity_decode($auteur->getCommentaire()) ?></td></tr>
<tr><td>Né le:</td><td><?php echo $auteur->getDateNaissance().' à '.$auteur->getLieuNaissance()?></td></tr>
<tr><td>Site Web:</td><td><?php echo $auteur->getWeb1() ?></td></tr>
<tr><td>Site Web:</td><td><?php echo $auteur->getWeb2() ?></td></tr>
<tr><td>Pays:</td><td><?php echo $auteur->getPays()->getNom() ?></td></tr>
<tr><td>Coloriste:</td><td><?php echo $auteur->getColoriste() ?></td></tr>
<tr><td>Dessinateur:</td><td><?php echo $auteur->getDessinateur() ?></td></tr>
<tr><td>Scenariste:</td><td><?php echo $auteur->getScenariste() ?></td></tr>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</tbody>
</table>