<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Consultation des Editeurs
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tbody>
<tr><td>Editeur:</td><td><?php echo $editeur->getNom() ?></td></tr>
<tr><td>Adresse :</td><td><?php echo $editeur->getAdresse1() ?></td></tr>
<tr><td></td><td><?php echo $editeur->getAdresse2() ?></td></tr>
<tr><td>Code Postal :</td><td><?php echo $editeur->getCP() ?></td></tr>
<tr><td>Ville:</td><td><?php echo $editeur->getVille() ?></td></tr>
<tr><td>Pays :</td><td><?php if ($editeur->getPays()) echo $editeur->getPays()->getNom() ?></td></tr>
<tr><td> </td><td><?php echo ($editeur->getPhoto1()==" ")?" ":image_tag($editeur->getPhoto1()) ?></td></tr>
<tr><td> </td><td><?php echo ($editeur->getPhoto2()==" ")?" ":image_tag($editeur->getPhoto2()) ?></td></tr>
<tr><td>Site Web:</td><td><?php echo $editeur->getSite() ?></td></tr>
<tr><td>Téléphone:</td><td><?php echo $editeur->getTel() ?></td></tr>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</tbody>
</table>