<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Consultation des Genres
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tbody>
<tr><td>Genre:</td><td><?php echo $genre->getNom() ?></td></tr>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</tbody>
</table>