<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/10/15 19:02:20
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_google_maps_api_keys' => array (
  'www.trocabd.com' => 'AIzaSyCeDejCLbn6UTrrqyTSYXup3mNcrMApU0I',
  'localhost' => 'AIzaSyCeDejCLbn6UTrrqyTSYXup3mNcrMApU0I',
),
));
