<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/10/15 19:02:21

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/trocabd',
), 'propel');
$this->databases['propel'] = $database;
