<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/10/15 19:02:45
$this->security = array (
  'show' => 
  array (
    'is_secure' => false,
  ),
  'showmap' => 
  array (
    'is_secure' => false,
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 'troqueur',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
