<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>

<table cellspacing=0 cellpadding=0>
<tr>
<?php if ($theTroc->getId()): ?>
<td>
<?php echo image_tag('bord_gauche_titre_edit.gif', array('border' => 0)) ?>
</td>
<td class="titrePageEdit">
Modification de Troc
</td>
<td>
<?php echo image_tag('bord_droite_titre_edit.gif', array('border' => 0,'background-position' => 'left')) ?>
</td>
<?php else: ?>
<td>
<?php echo image_tag('bord_gauche_titre_create.gif', array('border' => 0)) ?>
</td>
<td class="titrePageCreate">
Création de Troc
</td>
<td>
<?php echo image_tag('bord_droite_titre_create.gif', array('border' => 0,'background-position' => 'left')) ?>
</td>
<?php endif; ?>
</tr>
</table>
<?php echo object_input_hidden_tag($theTroc, 'getId') ?>
    <table width="607" height="459" border="1">
      <tr>
        <td width="290" height="26" colspan="2"><div align="center" class="Style8">Sa vitrine  </div></td>
        <td colspan="2"><div align="center" class="Style9">Ma vitrine </div></td>
      </tr>
      <tr>
<td id="sonOffre" height="27" colspan="2" valign="top">
<?php include_partial('offreList', array('liste' => $sonOffre)) ?>
</td>
        <td colspan="2" valign="top"><form id="form1" name="form1" method="post" action="">
          <label>
            <input type="checkbox" name="checkbox" value="checkbox" />
            Le décalogue II</label>
        </form>
          <form id="form1" name="form1" method="post" action="">
            <label>
            <input type="checkbox" name="checkbox2" value="checkbox" />
              Le d&eacute;calogue III</label>
          </form>
          <p align="right" class="Style9">&nbsp;</p></td>
      </tr>
      <tr>
        <td height="23" colspan="4" valign="top"><div align="right"><span class="Style9">Ajouter 
			les BD sélectionnées </span></div></td>
      </tr>
      <tr>
        <td height="58" colspan="4" valign="top"><div align="center" class="Style6">Notre troc </div></td>
        </tr>
      <tr>
        <td height="23" valign="top" class="Style8">Ses BD </td>
        <td colspan="2" valign="top" class="Style8"><div align="center" class="Style9">contre </div></td>
        <td width="249" valign="top" class="Style9"><div align="right">Mes BD </div></td>
      </tr>
      <tr>
        <td height="106" colspan="2" valign="top" id="items">
<?php include_partial('bdList', array('list' => 'my', 'thePager' => $myPager)) ?>
         </td>
      </tr>
      <tr>
        <td height="24" colspan="4" valign="top">
		<p align="right"><span class="Style9">Supprimer les BD sélectionnées
		</span></td>
      </tr>
    </table>
<?php echo drop_receiving_element('sonOffre', array('url' => 'gereTroc/addSonOffre', 'update' => 'sonOffre'))?>  
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
<?php if ($theTroc->getId()): ?>
  &nbsp;<?php echo link_to(image_tag('bt_supprimer', array('border' => 0)), 'gereTroc/delete?id='.$theTroc->getId().'&sort='.$sf_request->getParameter('sort'), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sort='.$sf_request->getParameter('sort')) ?>
<?php else: ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sort='.$sf_request->getParameter('sort')) ?>
<?php endif; ?>
