<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>
<?php use_helper('accordion');?>


<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($theTroc->getId()): ?>
Modification de Troc
<?php else: ?>
Création de Troc
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	

<table>
<tr>
<td>
<?php echo accordion("horizontal_container",array("direction"=>"horizontal"));?>

<div id="horizontal_container" >


    <h3 class="horizontal_accordion_toggle" style="text-align:left "></h3>
    <div class="horizontal_accordion_content" style="text-align:left ">
<div id="maVitrine" style="text-align:left ">
<?php include_partial('bdList', array('utilid' => $sf_request->getParameter('utilid'), 'list' => 'my', 'thePager' => $myPager, 'contexte' => 'MonOffre', 'vitrine' => 'maVitrine')) ?>
    </div>
    </div>
 


<div id="MonOffre" style="text-align:center ">
<?php include_partial('offreList', array('liste' => $monOffre, 'contexte' => 'MonOffre')) ?>
</div>



<div id="SonOffre" style="text-align:center ">
<?php include_partial('offreList', array('liste' => $sonOffre, 'contexte' => 'SonOffre')) ?>
</div>


    <h3 class="horizontal_accordion_toggle" style="text-align:right "></h3>
    <div class="horizontal_accordion_content" style="text-align:right ">
<div id="saVitrine" style="text-align:right ">
<?php include_partial('bdList', array('utilid' => $sf_request->getParameter('utilid'), 'list' => 'his', 'thePager' => $hisPager, 'contexte' => 'SonOffre', 'vitrine' => 'saVitrine')) ?>
    </div>
</div>

</div>
</td>
</tr>
</table>
