<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($theTroc->getId()): ?>
Modification de Troc
<?php else: ?>
Création de Troc
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	


<table>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</table>
<?php echo form_tag('gereTroc/update?sortTroc='.$sf_request->getParameter('sortTroc').'&utilid='.$sf_request->getParameter('utilid').'&nextEtatId='.$sf_request->getParameter('nextEtatId'), array('name' => 'formEditTroc')) ?>
<?php echo object_input_hidden_tag($theTroc, 'getId') ?>
    <table width="880" height="459" >
      <tr>
        <td height="58" align="center" colspan="4" valign="top"><div class="Style6">Troc</div> (cliquez sur "-" pour retirer une BD)</td>
        </tr>
      <tr>
        <td height="23" valign="top" class="listeObjetTitreTableau"><div align="center"><?php echo $sf_user->getAttribute('login') ?></div></td>
        <td colspan="2" valign="top" class="listeObjetTitreTableau"><div align="center" class="Style9">échange avec </div></td>
        <td  valign="top" class="listeObjetTitreTableau"><div align="center"> <?php echo $hisLogin ?></div></td>
      </tr>
       <tr>
<td id="MonOffre" height="27" valign="top">
<?php include_partial('offreList', array('liste' => $monOffre, 'contexte' => 'MonOffre')) ?>
</td>
         <td colspan="2"></td>
<td id="SonOffre" height="27" valign="top" >
<?php include_partial('offreList', array('liste' => $sonOffre, 'contexte' => 'SonOffre')) ?>
</td>
      </tr>
        <tr>
        <td height="58" align="center" colspan="4" valign="top"><div class="Style6">Vitrines </div>(cliquez sur "+" pour ajouter une BD)</td>
        </tr>
      <tr>
        <td  height="26" ><div align="center" class="listeObjetTitreTableau"><?php echo 'Ma vitrine ('.$sf_user->getAttribute('login').')'  ?></div></td>
          <td colspan="2"></td>
        <td ><div align="center" class="listeObjetTitreTableau"><?php echo 'Sa vitrine ('.$hisLogin.')'  ?></div></td>
      </tr>
       <tr>
        <td height="106" valign="top" id="maVitrine">
<?php include_partial('bdList', array('utilid' => $sf_request->getParameter('utilid'), 'list' => 'my', 'thePager' => $myPager, 'contexte' => 'MonOffre', 'vitrine' => 'maVitrine')) ?>
         </td>
         <td colspan="2"></td>
        <td height="106" valign="top" id="saVitrine">
<?php include_partial('bdList', array('utilid' => $sf_request->getParameter('utilid'), 'list' => 'his', 'thePager' => $hisPager, 'contexte' => 'SonOffre', 'vitrine' => 'saVitrine')) ?>
         </td>
      </tr>
    </table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
<?php if ($theTroc->getId()): ?>
  &nbsp;<?php echo link_to(image_tag('bt_supprimer', array('border' => 0)), 'gereTroc/delete?id='.$theTroc->getId().'&sortTroc='.$sf_request->getParameter('sortTroc'), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sortTroc='.$sf_request->getParameter('sortTroc')) ?>
<?php else: ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sortTroc='.$sf_request->getParameter('sortTroc')) ?>
<?php endif; ?>
</form>
