<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Coordonnées du destinataire
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tbody>
<?php echo form_tag('gereTroc/nextStep?nextEtatId='.$sf_request->getParameter('nextEtatId').'&id='.$sf_request->getParameter('id').'&sortTroc='.$sf_request->getParameter('sortTroc').'&utilid='.$sf_request->getParameter('utilid'), array('name' => 'formExpedier')) ?>
<?php include_partial('gereUtilisateur/adresse', array('user' => $user)) ?>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sortTroc='.$sf_request->getParameter('sortTroc')) ?>
