<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
// <link rel="stylesheet" href="/css/moorating.css" />

?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>


<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Liste des Trocs
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tr><td colspan=2 >
<?php echo $pager->getNbResults() ?> résultats trouvés.<br/>
Affichage des résultats <?php echo $pager->getFirstIndice() ?> à  <?php echo $pager->getLastIndice() ?>.
</td></tr>
<thead class="listeObjetTitreTableau">
<tr>
  <th><?php echo link_to ('Date Création', 'gereTroc/list?sortTroc=created_at') ?></th>
  <th><?php echo link_to ('Troqueur', 'gereTroc/list?sortTroc=nom') ?></th>
  <th><?php echo link_to ('Etat', 'gereTroc/list?sortTroc=etat_id') ?></th>
  <th><?php echo 'Votre note' ?></th>
  <th>Action</th>
</tr>
</thead>
<tbody class="listeObjetLigneTableau">
<?php $i=0 ?>
<?php foreach ($pager->getResults() as $obj): ?>
<tr>
      <td><?php echo $obj->getCreatedAt() ?></td>
      <?php if($obj->getUtilisateursource()->getUtilisateurID()==$sf_user->getAttribute('id') and ($sf_user->isAuthenticated())): ?>
	      <?php $acteur = 'SOURCE' ?>
	      <?php $myLogin = $obj->getUtilisateursource()->getUtilisateur()->getLogin() ?>
	      <?php $myUtilid = $obj->getUtilisateursource()->getUtilisateurId() ?>
	      <?php $hisLogin = $obj->getUtilisateurCible()->getUtilisateur()->getLogin() ?>
	      <?php $hisUtilid = $obj->getUtilisateurCible()->getUtilisateurId() ?>
	      <td><?php echo link_to($obj->getUtilisateurCible()->getUtilisateur()->getLogin(), 'gereBD/saVitrine?login='.$hisLogin.'&utilid='.$hisUtilid) ?></td>
      <?php else: ?>     
	      <?php $acteur = 'CIBLE' ?>
	      <?php $myLogin = $obj->getUtilisateurCible()->getUtilisateur()->getLogin() ?>
	      <?php $myUtilid = $obj->getUtilisateurCible()->getUtilisateurId() ?>
	      <?php $hisLogin = $obj->getUtilisateurSource()->getUtilisateur()->getLogin() ?>
	      <?php $hisUtilid = $obj->getUtilisateurSource()->getUtilisateurId()?>
	      <td><?php echo link_to($obj->getUtilisateurSource()->getUtilisateur()->getLogin() , 'gereBD/saVitrine?login='.$hisLogin.'&utilid='.$hisUtilid) ?></td>
      <?php endif; ?>
      <td><?php echo process::getEtat($obj->getEtatId(), $acteur) ?> </td>
      <?php if($obj->getUtilisateurSource()->getUtilisateurId()==$sf_user->getAttribute('id')): ?>
	      <td><?php echo image_tag('/images/rate_'.$obj->getUtilisateurSource()->getNote().'.gif') ?></td>
       <?php else: ?>     
	      <td><?php echo image_tag('/images/rate_'.$obj->getUtilisateurCible()->getNote().'.gif') ?></td>
	  <?php endif; ?>
      <td>
      <?php echo '&nbsp' ?>
      <?php if($sf_user->hasCredential('troqueur')): ?>
		<?php foreach ((array)process::getTransitions($obj->getEtatId(), $acteur) as $ktra => $vtra): ?>
		    <?php if($vtra['tag']=='L'): ?>
				<?php echo link_to ($ktra, $vtra['url'].'id='.$obj->getId().'&sortTroc='.$sortTroc.'&utilid='.$hisUtilid.'&login='.$myLogin) ?>
		    <?php endif; ?>
			<?php echo '&nbsp' ?>
		<?php endforeach; ?>
      <?php endif; ?>
<?php // if($sf_user->isAuthenticated()): ?>
	 <?php echo link_to (image_tag('bt_voir', array('border' => 0)), 'gereTroc/show?id='.$obj->getId().'&sortTroc='.$sortTroc.'&login='.$myLogin)?>
<?php // endif; ?>

      </td>
</tr>
<?php endforeach; ?>
</tbody>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><?php echo $sf_flash->get('messageFin')?></tr>
<?php endif; ?>
</table>
<?php $param='' ?>
<?php if  ($sf_request->getParameter('sort')):?>
<?php      $param='$sort='.$sf_request->getParameter('sort') ?>
<?php endif; ?>

<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to('&laquo;', 'gereTroc/list?page='.$pager->getFirstPage().'&sortTroc='.$sortTroc) ?>
  <?php echo link_to('&lt;', 'gereTroc/list?page='.$pager->getPreviousPage().'&sortTroc='.$sortTroc) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, 'gereTroc/list?page='.$page.'&sortTroc='.$sortTroc) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?> - <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('&gt;', 'gereTroc/list?page='.$pager->getNextPage().'&sortTroc='.$sortTroc) ?>
  <?php echo link_to('&raquo;', 'gereTroc/list?page='.$pager->getLastPage().'&sortTroc='.$sortTroc) ?>
<?php endif ?>

