<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Notez le troc
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	
    <table width="880" height="200" >
      <tr>
        <td height="58" align="center" colspan="4" valign="top"><div class="Style6">Troc</div> </td>
        </tr>
      <tr>
        <td height="23" valign="top" class="listeObjetTitreTableau"><div align="center"><?php echo $sf_user->getAttribute('login') ?></div></td>
        <td colspan="2" valign="top" class="listeObjetTitreTableau"><div align="center" class="Style9">échange avec </div></td>
        <td  valign="top" class="listeObjetTitreTableau"><div align="center"> <?php echo $hisLogin ?></div></td>
      </tr>
       <tr>
<td id="monOffre" height="27"  valign="top">
<?php include_partial('offreList', array('liste' => $monOffre, 'contexte' => 'monOffre')) ?>
</td>
         <td colspan="2"></td>
<td id="sonOffre" height="27"  valign="top">
<?php include_partial('offreList', array('liste' => $sonOffre, 'contexte' => 'sonOffre')) ?>
</td>
      </tr>
    </table>
<?php echo form_tag('gereTroc/updatenote?sortTroc='.$sf_request->getParameter('sortTroc').'&utilid='.$sf_request->getParameter('utilid').'&nextEtatId='.$sf_request->getParameter('nextEtatId').'&login='.$sf_request->getParameter('login'), array('name' => 'formUpdatenotetroc')) ?>
<?php echo object_input_hidden_tag($theTroc, 'getId') ?>
<table>
<tbody>
<tr><td colspan="2" ><?php echo form_error('note') ?></td></tr>
<tr><td></td><td>		 <?php echo object_input_hidden_tag($theUser, 'getNote', array ('size' => 2,)) ?></td></tr>
</tbody>
</table>



<div id="track1" class="track" >
   <div id="handle1" class="handle"  ></div>
</div>

<p id="sliding" ></p>
<p id="changed" ></p>

  <?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sortTroc='.$sf_request->getParameter('sortTroc')) ?>
  