<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>
<?php use_helper('Javascript') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Consultation de Troc
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	


<table>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</table>
<?php echo object_input_hidden_tag($theTroc, 'getId') ?>
    <table width="880" height="200" >
      <tr>
        <td height="58" align="center" colspan="4" valign="top"><div class="Style6">Troc</div> </td>
        </tr>
      <tr>
        <td height="23" valign="top" class="listeObjetTitreTableau"><div align="center"><?php echo $myLogin ?></div></td>
        <td colspan="2" valign="top" class="listeObjetTitreTableau"><div align="center" class="Style9">échange avec </div></td>
        <td  valign="top" class="listeObjetTitreTableau"><div align="center"> <?php echo $hisLogin ?></div></td>
      </tr>
       <tr>
<td id="monOffre" height="27"  valign="top">
<?php include_partial('offreList', array('liste' => $monOffre, 'contexte' => 'monOffre')) ?>
</td>
         <td colspan="2"></td>
<td id="sonOffre" height="27"  valign="top">
<?php include_partial('offreList', array('liste' => $sonOffre, 'contexte' => 'sonOffre')) ?>
</td>
      </tr>
    </table>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereTroc/list?sortTroc='.$sf_request->getParameter('sortTroc')) ?>
