<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Liste des BD
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tr><td>
<?php echo $pager->getNbResults() ?> résultats trouvés.<br/>
Affichage des résultats <?php echo $pager->getFirstIndice() ?> à  <?php echo $pager->getLastIndice() ?>.
</td></tr>

<thead class="listeObjetTitreTableau">
<tr>
  <th></th>
  <th><?php echo link_to ('Serie', 'gereBD/'.$sf_request->getContext()->getActionName().'?sort=Nom&utilid='.$sf_request->getParameter('utilid')) ?></th>
  <th><?php echo link_to ('Titre', 'gereBD/'.$sf_request->getContext()->getActionName().'?sort=Talbum&utilid='.$sf_request->getParameter('utilid')) ?></th>
  <th><?php echo link_to ('Date Parution', 'gereBD/'.$sf_request->getContext()->getActionName().'?sort=DateParu&utilid='.$sf_request->getParameter('utilid')) ?></th>
  <th>Action</th>
</tr>
</thead>
<tbody class="listeObjetLigneTableau">
<?php foreach ($pager->getResults() as $obj): ?>
<tr>
	  <td><?php echo image_tag(UPLOAD_BD_DIR_REL.'/'.$obj->getAlbum()->getPhoto1(),SIZE_THUMBS) ?></td>
      <td><?php echo $obj->getAlbum()->getSerie()->getNom() ?></td>
      <td><?php echo $obj->getAlbum()->getTalbum() ?></td>
      <td><?php echo $obj->getAlbum()->getDateParu()?></td>
      <td>
      <?php if(($sf_user->getAttribute('id')== $sf_request->getParameter('utilid')) ): ?>
		<u>
		<?php //echo link_to (image_tag('bt_modifier', array('border' => 0)), 'gereBD/edit?id='.$obj->getAlbum()->getId().'&sort='.$sf_request->getParameter('sort'))?></u>
		   <?php $exOfr = 'N' ?>
	       <?php if(($obj->getAlbum()->countOffresources()>0)): ?>
				<?php foreach ($obj->getAlbum()->getOffresources() as $ofrs): ?>
			       <?php if(($ofrs->getUtilisateursource()->getUtilisateurId()==$sf_request->getParameter('utilid'))): ?>
			       		<?php $exOfr = 'O' ?>
			       <?php endif; ?>
				<?php endforeach; ?>
	       <?php endif; ?>
	       <?php if(($obj->getAlbum()->countOffrecibles()>0)): ?>
				<?php foreach ($obj->getAlbum()->getOffrecibles() as $ofrc): ?>
			       <?php if(($ofrc->getUtilisateurcible()->getUtilisateurId()==$sf_request->getParameter('utilid'))): ?>
			       		<?php $exOfr = 'O' ?>
			       <?php endif; ?>
				<?php endforeach; ?>
	       <?php endif; ?>
           <?php if($exOfr == 'N'): ?>
				<u><?php echo link_to (image_tag('bt_retirer', array('border' => 0)), 'gereBD/retirerVitrine?id='.$obj->getId().'&sort='.$sf_request->getParameter('sort'))?></u>
	       <?php endif; ?>
      <?php endif; ?>
      <?php if(!($sf_user->getAttribute('id')== $sf_request->getParameter('utilid'))): ?>
		<u><?php echo link_to (image_tag('bt_voir', array('border' => 0)), 'gereBD/show?id='.$obj->getAlbum()->getId().'&sort='.$sf_request->getParameter('sort'))?></u>
      <?php endif; ?>
</tr>
<?php endforeach; ?>
</tbody>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><?php echo $sf_flash->get('messageFin')?></tr>
<?php endif; ?>
</table>
<?php if(($sf_user->hasCredential('admin')) and ($sf_user->getAttribute('id')== $sf_request->getParameter('utilid'))): ?>
   <?php echo link_to (image_tag('bt_ajouterBD', array('border' => 0)), 'gereBD/create?sort='.$sf_request->getParameter('sort'))?>
<?php endif; ?>

<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to('&laquo;', 'gereBD/'.$sf_request->getContext()->getActionName().'?page='.$pager->getFirstPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
  <?php echo link_to('&lt;', 'gereBD/'.$sf_request->getContext()->getActionName().'?page='.$pager->getPreviousPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, 'gereBD/'.$sf_request->getContext()->getActionName().'?page='.$page.'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?> - <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('&gt;', 'gereBD/'.$sf_request->getContext()->getActionName().'?page='.$pager->getNextPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
  <?php echo link_to('&raquo;', 'gereBD/'.$sf_request->getContext()->getActionName().'?page='.$pager->getLastPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
<?php endif ?>

