<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:02
?>
<?php

/**
 * gereBD actions.
 *
 * @package    trocabd
 * @subpackage gereTroc
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class gereTrocActions extends sfActions
{


public function executeIndex()
  {
  	return $this->forward('gereTroc', 'list');
  }
  

  public function executeList()
  {
  	if ($this->getRequestParameter('sortTroc'))
  	{
  		$this->sortTroc=$this->getRequestParameter('sortTroc');
  	}
  	else
  	{
  		$this->sortTroc='created_at';
  	}
  	$c = new Criteria();
 	$c->addDescendingOrderByColumn($this->sortTroc);
  	
	$c->addjoin(TrocPeer::UTILISATEURSOURCE_ID, UtilisateursourcePeer::ID);
	$c->addjoin(UtilisateursourcePeer::UTILISATEUR_ID, UtilisateurPeer::ID, Criteria::LEFT_JOIN);
	$c->addjoin(UtilisateursourcePeer::ID, OffresourcePeer::UTILISATEURSOURCE_ID, Criteria::LEFT_JOIN);
 	$c->setDistinct(); 
 	$c->addAlias('T1', UtilisateurPeer::TABLE_NAME);
 	$c->addAsColumn('nom','T1.nom');
 	$c->addAsColumn('nom','utilisateur.nom');
 	$c->addjoin(TrocPeer::UTILISATEURCIBLE_ID, UtilisateurciblePeer::ID);
	$c->addjoin(UtilisateurciblePeer::UTILISATEUR_ID, UtilisateurPeer::alias('T1',UtilisateurPeer::ID), Criteria::LEFT_JOIN);
	$c->addjoin(UtilisateurciblePeer::ID, OffreciblePeer::UTILISATEURCIBLE_ID, Criteria::LEFT_JOIN);
	
	if ($this->getUser()->isAuthenticated())
	{
	 	$crit1 = $c->getNewCriterion(UtilisateurPeer::ID, $this->getUser()->getAttribute('id'));
		$crit1->addOr($c->getNewCriterion(UtilisateurPeer::alias('T1',UtilisateurPeer::ID), $this->getUser()->getAttribute('id')));
		$c->add($crit1);
	}
	
	$pager = new sfPropelPager('Troc', 5);
    $pager->setCriteria($c);
    $pager->setPage($this->getRequestParameter('page', 1));
    $pager->init();
    $this->pager = $pager;
  }


  public function executeShow()
  {
    $this->theTroc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->theTroc);
    $this->monOffre = array();
   	$this->sonOffre = array();
   	
	if ($this->theTroc->getUtilisateursource()->getUtilisateurId()==$this->getUser()->getAttribute('id')) {
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateurcible()->getUtilisateur()->getLogin();
	} else {
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateursource()->getUtilisateur()->getLogin();
	}
	   	
   	$this->getUser()->setAttribute('sonOffre', $this->sonOffre);
    $this->myPager = $this->buildMyPager();
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
    $this->hisPager = $this->buildHisPager();
  }
  
  private function setTabOffre($dataOffre) {
    $tabOffre = array();
    $rpl = array("+l%26#039;", "\""); 
  	foreach ($dataOffre as $uneOffre)
   	{
   		$album['albumTitre']=str_replace($rpl, '', $uneOffre->getAlbum()->getTalbum());
   		$album['albumId']=$uneOffre->getAlbum()->getId();
    	$tabOffre[$uneOffre->getAlbum()->getId()]=$album;
   	}
  	return $tabOffre;  
  }

  
  public function executeAddSonOffre()
  {
//    $tmp = split('_', $this->getRequestParameter('id', ''));
//    $this->possId = $tmp[1];
    $tmp = split('_', $this->getRequestParameter('albumId', ''));
    $this->albumId = $tmp[1];
    $this->sonOffre = $this->getUser()->getAttribute('sonOffre');
    $titre = $this->getRequestParameter('titre', '');
    $this->alb =  array();
    $this->alb['albumId']=$this->albumId;
    $rpl = array("+l%26#039;", "\""); 
    $this->alb['albumTitre']=str_replace($rpl, '', $titre);
    $this->sonOffre[$this->albumId] = $this->alb;
    $this->getUser()->setAttribute('sonOffre', $this->sonOffre);
	$this->setFlash('actionOrigine',$this->getFlash('actionOrigine'));
	$this->setFlash('messageOrigine',$this->getFlash('messageOrigine'));
  }
   
  public function executeSubstrSonOffre()
  {
//    $tmp = split('_', $this->getRequestParameter('id', ''));
//    $this->possId = $tmp[1];
    $tmp = split('_', $this->getRequestParameter('albumId', ''));
    $this->albumId = $tmp[1];
    $this->sonOffre = $this->getUser()->getAttribute('sonOffre');
    unset($this->sonOffre[$this->albumId]);
    $this->getUser()->setAttribute('sonOffre', $this->sonOffre);
    $this->setTemplate('addSonOffre');
	$this->setFlash('actionOrigine',$this->getFlash('actionOrigine'));
	$this->setFlash('messageOrigine',$this->getFlash('messageOrigine'));
  }
   
  public function executeAddMonOffre()
  {
//    $tmp = split('_', $this->getRequestParameter('id', ''));
//    $this->possId = $tmp[1];
    $tmp = split('_', $this->getRequestParameter('albumId', ''));
    $this->albumId = $tmp[1];
    $this->monOffre = $this->getUser()->getAttribute('monOffre');
    $titre = $this->getRequestParameter('titre', '');
    $this->alb =  array();
    $this->alb['albumId']=$this->albumId;
    $rpl = array("+l%26#039;", "\""); 
    $this->alb['albumTitre']=str_replace($rpl, '', $titre);
    $this->monOffre[$this->albumId] = $this->alb;
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
	$this->setFlash('actionOrigine',$this->getFlash('actionOrigine'));
	$this->setFlash('messageOrigine',$this->getFlash('messageOrigine'));
  }
   
  public function executeSubstrMonOffre()
  {
//    $tmp = split('_', $this->getRequestParameter('id', ''));
//    $this->possId = $tmp[1];
    $tmp = split('_', $this->getRequestParameter('albumId', ''));
    $this->albumId = $tmp[1];
    $this->monOffre = $this->getUser()->getAttribute('monOffre');
    unset($this->monOffre[$this->albumId]);
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
    $this->setTemplate('addMonOffre');
 	$this->setFlash('actionOrigine',$this->getFlash('actionOrigine'));
	$this->setFlash('messageOrigine',$this->getFlash('messageOrigine'));
  }
    
  public function executeBdList()
  {
  if ($this->getRequestParameter('list')=='my')
  	{
  		$this->myPager = $this->buildMyPager();
	   	$this->setTemplate('myBdList');
	}
  if ($this->getRequestParameter('list')=='his')
  	{
  		$this->hisPager = $this->buildHisPager();
	   	$this->setTemplate('hisBdList');
	}
  }
  
  private function buildMyPager()
  {
  	$c = new Criteria();
  	$c->addJoin(PossedePeer::ALBUM_ID, AlbumPeer::ID, 'JOIN');
  	$c->add(PossedePeer::UTILISATEUR_ID, $this->getUser()->getAttribute('id'));
	$pager = new sfPropelPager('Possede', 5);
	
    $pager->setCriteria($c);
    $pager->setPage($this->getRequestParameter('page', 1));
    $pager->init();
    return $pager;
  }

  
  private function buildHisPager()
  {
  	$c = new Criteria();
  	$c->addJoin(PossedePeer::ALBUM_ID, AlbumPeer::ID, 'JOIN');
  	$c->add(PossedePeer::UTILISATEUR_ID, $this->getRequestParameter('utilid'));
	$pager = new sfPropelPager('Possede', 5);
	
    $pager->setCriteria($c);
    $pager->setPage($this->getRequestParameter('page', 1));
    $pager->init();
    return $pager;
  }
  
  public function executeCreate()
  {
    $this->theTroc = new Troc();
    $this->sonOffre = array();
   	$this->getUser()->setAttribute('sonOffre', $this->sonOffre);
    $this->myPager = $this->buildMyPager();
    $this->monOffre = array();
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
    $this->hisPager = $this->buildHisPager();
    if ($this->getRequestParameter('id'))
    {
    	$this->executeAddSonOffre();
    }
	$this->hisLogin=$this->hisPager->getCurrent()->getUtilisateur()->getLogin();
    
    $this->setFlash('actionOrigine','create');
	$this->setFlash('messageOrigine',MESSAGE_FIN_CREATE_OK);
    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->theTroc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
   	$this->forward404Unless($this->theTroc);
   	$this->monOffre = array();
   	$this->sonOffre = array();
   	
	if ($this->theTroc->getUtilisateursource()->getUtilisateurId()==$this->getUser()->getAttribute('id')) {
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateurcible()->getUtilisateur()->getLogin();
	} else {
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateursource()->getUtilisateur()->getLogin();
	}
   	
	$this->getUser()->setAttribute('sonOffre', $this->sonOffre);
    $this->myPager = $this->buildMyPager();
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
    $this->hisPager = $this->buildHisPager();
   	$this->setFlash('actionOrigine','edit');
	$this->setFlash('messageOrigine',MESSAGE_FIN_EDIT_OK);
   }
  
  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $troc = new Troc();
      $troc->setEtatId(2);
      $troc->save();
      
      $usource = new Utilisateursource();
      $usource->setUtilisateurId($this->getUser()->getAttribute('id'));
      $usource->setNote(0);
      $usource->setTrocId($troc->getId());
      $usource->save();
      
      $ucible = new Utilisateurcible(); 
      $ucible->setUtilisateurId($this->getRequestParameter('utilid')); 
      $ucible->setNote(0);
      $ucible->setTrocId($troc->getId());
      $ucible->save();
      
      $troc->setUtilisateursourceId($usource->getId());
      $troc->setUtilisateurcibleId($ucible->getId());
      $troc->save();
    }
    else
    {
      $troc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($troc);
    
	  $offre = $troc->getUtilisateursource()->getOffresources();
	  foreach ($offre as $uneOffre)
	  {
	  	$uneOffre->delete();
	  }
	  $offre = $troc->getUtilisateurcible()->getOffrecibles();
	  foreach ($offre as $uneOffre)
	  {
	  	$uneOffre->delete();
	  }
	  
	  if ($this->getRequestParameter('nextEtatId')) {
	    $nextEtatId = $this->getRequestParameter('nextEtatId');
	    $troc->setEtatId($nextEtatId);
	    $troc->save();
	  }
    }
	   	
    $this->sonOffre = $this->getUser()->getAttribute('sonOffre');
	$this->monOffre = $this->getUser()->getAttribute('monOffre');

	if ($troc->getUtilisateursource()->getUtilisateurId()==$this->getUser()->getAttribute('id')) {
//		$os = new Offresource();
		$this->saveOffreSource($this->monOffre, $troc->getUtilisateursource()->getId() );
		$this->saveOffreCible($this->sonOffre, $troc->getUtilisateurcible()->getId() );
	} else {
		$this->saveOffreSource($this->sonOffre, $troc->getUtilisateursource()->getId() );
		$this->saveOffreCible($this->monOffre, $troc->getUtilisateurcible()->getId() );
	}
   	
	
	
	$this->setFlash('messageFin',$this->getFlash('messageOrigine'));
    $this->redirect('gereTroc/list?sortTroc='.$this->sortTroc);
  }

  private function saveOffreSource($tabOffre, $userId) {
  	foreach ( $tabOffre as $key => $album )
	{
		$offreSource = new Offresource();
		$offreSource->setAlbumId($key);
	 	$offreSource->setUtilisateursourceId($userId);
	 	$offreSource->save();
	}
  }

  private function saveOffreCible($tabOffre, $userId) {
  	foreach ( $tabOffre as $key => $album )
	{
		$offreCible = new Offrecible();
		$offreCible->setAlbumId($key);
	 	$offreCible->setUtilisateurcibleId($userId);
	 	$offreCible->save();
	}
  }
  
  
  public function executeNextStep()
  {
    $troc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($troc);
    $nextEtatId = $this->getRequestParameter('nextEtatId');
    $troc->setEtatId($nextEtatId);
    $troc->save();
    
	$this->setFlash('messageFin',$this->getFlash('messageOrigine'));
    $this->redirect('gereTroc/list?sortTroc='.$this->sortTroc);
  }
  
  public function executeExpedier()
  {
    $this->user = UtilisateurPeer::retrieveByPk($this->getRequestParameter('utilid'));
    $this->forward404Unless($this->user);
   }


  public function executeNoter()
  {
		$prototypeDir = sfConfig::get('sf_prototype_web_dir');
		$this->getResponse()->addJavascript($prototypeDir.'/js/prototype.js');
		$this->getResponse()->addJavascript($prototypeDir.'/js/scriptaculous.js');
		$this->getResponse()->addJavascript($prototypeDir.'/js/slider.js');
		
  
    $this->theTroc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
   	$this->forward404Unless($this->theTroc);

   	
   	if ($this->theTroc->getUtilisateurcible()->getUtilisateurId()<>$this->getUser()->getAttribute('id'))
    {
		$this->theUser=$this->theTroc->getUtilisateursource();
 	}
    else
    {
	    $this->theUser=$this->theTroc->getUtilisateurcible();
    }
   	
   	$this->monOffre = array();
   	$this->sonOffre = array();
   	
	if ($this->theTroc->getUtilisateursource()->getUtilisateurId()==$this->getUser()->getAttribute('id')) {
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateurcible()->getUtilisateur()->getLogin();
	} else {
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateursource()->getUtilisateur()->getLogin();
	}
   	
   	
   	$this->getUser()->setAttribute('sonOffre', $this->sonOffre);
    $this->myPager = $this->buildMyPager();
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
    $this->hisPager = $this->buildHisPager();
   	$this->setFlash('actionOrigine','noter');
	$this->setFlash('messageOrigine',MESSAGE_FIN_EDIT_OK);
   }
   
  public function executeUpdatenote()
  {
    $troc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($troc);
    $nextEtatId = $this->getRequestParameter('nextEtatId');
    $troc->setEtatId($nextEtatId);
    if ($troc->getUtilisateursource()->getUtilisateurId()<>$this->getUser()->getAttribute('id'))
    {
		$troc->getUtilisateurcible()->setNote($this->getRequestParameter('note'));
 	}
    else
    {
		$troc->getUtilisateursource()->setNote($this->getRequestParameter('note'));
    }
    $troc->save();
    
// transfert des livres reçus dans la vitrine de l'utilisateur
//	$message = 'utilid='.$this->getRequestParameter('utilid');
    $offre = $this->getUser()->getAttribute('sonOffre');
   	foreach ($offre as $key => $album)
   	{
	  	$c = new Criteria();
	   	$c->add(PossedePeer::UTILISATEUR_ID, $this->getRequestParameter('utilid'));
	   	$c->add(PossedePeer::ALBUM_ID, $key);
//	    $nbPoss = PossedePeer::doCount($c);
	    if (	$possede = PossedePeer::doSelectOne($c)) {
	  	  	$possede->setUtilisateurId($this->getUser()->getAttribute('id'));
	    	$possede->save();
	   	}
//		$message.='key='.$key.'nbPoss='.$nbPoss;
   	}
   	
	$this->setFlash('messageFin',$this->getFlash('messageOrigine'));
//	$this->setFlash('messageFin',$message);
	$this->redirect('gereTroc/list?sortTroc='.$this->sortTroc);
  }
   
  
  public function executeDelete()
  {
    $troc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($troc);
    $us = $troc->getUtilisateursource();
    $uc = $troc->getUtilisateurcible();
    $ofrs = $us->getOffresources();
    foreach ($ofrs as $of) 
    {
    	$of->delete();
    }
    $ofrc = $uc->getOffrecibles();
    foreach ($ofrc as $of) 
    {
    	$of->delete();
    }
    $troc->delete();
    $us->delete();
    $uc->delete();
    $this->setFlash('messageFin',MESSAGE_FIN_DELETE_OK);
    return $this->redirect('gereTroc/list'.'?sortTroc='.$this->sortTroc);
  }
  
  public function handleErrorUpdate()
  {
    $this->theTroc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
  	if (!$this->theTroc)
  	{
  	 	    $this->theTroc = new Troc();
  	}
  	
  	
    $this->sonOffre = array();
    $this->myPager = $this->buildMyPager();
    $this->monOffre = array();
    $this->hisPager = $this->buildHisPager();
  	
	$this->setFlash('actionOrigine',$this->getFlash('actionOrigine'));
	$this->setFlash('messageOrigine',$this->getFlash('messageOrigine'));
  	
	$this->setTemplate('edit');
   	return sfView::SUCCESS;
  }
    
  public function handleErrorUpdatenote()
  {
    $this->theTroc = TrocPeer::retrieveByPk($this->getRequestParameter('id'));
  	if (!$this->theTroc)
  	{
  	 	    $this->theTroc = new Troc();
  	}
  	
//    if ($this->theTroc->getUtilisateur()->getId()<>$this->getUser()->getAttribute('id'))
//    {
//		$this->getter='getNotecible';
// 	}
//    else
//    {
//		$this->getter='getNotesource';
//        }
   	
   	$this->monOffre = array();
   	$this->sonOffre = array();
   	
	if ($this->theTroc->getUtilisateursource()->getUtilisateurId()==$this->getUser()->getAttribute('id')) {
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateurcible()->getUtilisateur()->getLogin();
	} else {
	   	$this->sonOffre=$this->setTabOffre($this->theTroc->getUtilisateursource()->getOffresources());
	   	$this->monOffre=$this->setTabOffre($this->theTroc->getUtilisateurcible()->getOffrecibles());
	    $this->hisLogin=$this->theTroc->getUtilisateursource()->getUtilisateur()->getLogin();
	}
	
   	$this->getUser()->setAttribute('sonOffre', $this->sonOffre);
    $this->myPager = $this->buildMyPager();
    $this->getUser()->setAttribute('monOffre', $this->monOffre);
    $this->hisPager = $this->buildHisPager();
    $this->setFlash('actionOrigine',$this->getFlash('actionOrigine'));
	$this->setFlash('messageOrigine',$this->getFlash('messageOrigine'));
	$this->setTemplate('noter');
   	return sfView::SUCCESS;
  }
  
  public function executeHorizontal()
  {

  }
  
}
