<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($communaute->getId()): ?>
Modification de communaute
<?php else: ?>
Création de communaute
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	

<?php echo form_tag('gereCommunaute/update?sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid'), array('name' => 'formCommunaute')) ?>
<?php echo object_input_hidden_tag($communaute, 'getId') ?>
<table>
<tbody>
<tr><td><?php echo form_error('ncommunaute') ?></td></tr>
<tr><td>Nom :</td><td>		 <?php echo object_input_tag($communaute, 'getNcommunaute', array ('size' => 25,)) ?></td></tr>
<tr><td><?php echo form_error('devise') ?></td></tr>
<tr><td>Devise :</td><td>		 <?php echo object_input_tag($communaute, 'getDevise', array ('size' => 50,)) ?></td></tr>
<tr><td><?php echo form_error('description') ?></td></tr>
<tr><td>Description :</td><td>		 <?php echo object_textarea_tag($communaute, 'getDescription', array ('size' => '30x10')) ?></td></tr>
</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'gereCommunaute/list?sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
