<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Liste des Communautés
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tr><td>
<?php echo $pager->getNbResults() ?> résultats trouvés.<br/>
Affichage des résultats <?php echo $pager->getFirstIndice() ?> à  <?php echo $pager->getLastIndice() ?>.
</td></tr>

<thead class="listeObjetTitreTableau">
<tr>
  <th><?php echo link_to ('Communauté', 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?sort=nCommunaute&utilid='.$sf_request->getParameter('utilid')) ?></th>
  <th><?php echo link_to ('Créateur', 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?sort=Login&utilid='.$sf_request->getParameter('utilid')) ?></th>
  <th>Action</th>
</tr>
</thead>
<tbody class="listeObjetLigneTableau">
<?php foreach ($pager->getResults() as $obj): ?>
<tr>
      <td><?php echo $obj->getNCommunaute() ?></td>
      <td><?php echo $obj->getUtilisateur()->getLogin() ?></td>
      <td>
      <?php if(($sf_user->getAttribute('id')== $obj->getUtilisateurId()) ): ?>
		
		   <?php echo link_to (image_tag('bt_modifier', array('border' => 0)), 'gereCommunaute/edit?id='.$obj->getId().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid'))?>
		   <?php echo link_to (image_tag('bt_inviter', array('border' => 0)), 'gereUtilisateur/recherche?sort=nom&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$obj->getId().'&communautecreateurid='.$obj->getUtilisateurId().'&communauteName='.$obj->getNcommunaute())?>
           <?php if($obj->countMembres()==1): ?>
				<?php echo link_to (image_tag('bt_supprimer', array('border' => 0)), 'gereCommunaute/delete?id='.$obj->getId().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid'))?>
	       <?php endif; ?>
      <?php else: ?>
			<?php 
			$cMembre = new Criteria();
			$cMembre->add(MembrePeer::UTILISATEUR_ID, $sf_user->getAttribute('id'));
			$rMembre = $obj->getMembres($cMembre);
			$idMembre = $rMembre[0]->getId();
			?>
            <?php if($rMembre[0]->getMembre()==0): ?>
				<?php echo 'vous êtes invités : ' ?>
				<?php echo link_to (image_tag('bt_accepter', array('border' => 0)), 'gereCommunaute/accepterInvite?id='.$idMembre.'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$obj->getId())?>
				<?php echo link_to (image_tag('bt_refuser', array('border' => 0)), 'gereCommunaute/quitter?id='.$idMembre.'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$obj->getId())?>
     		<?php else: ?>
				<?php echo link_to (image_tag('bt_quitter', array('border' => 0)), 'gereCommunaute/quitter?id='.$idMembre.'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$obj->getId())?>
	        <?php endif; ?>
        <?php endif; ?>
		<?php echo link_to (image_tag('bt_voir', array('border' => 0)), 'gereCommunaute/show?id='.$obj->getId().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid'))?>
</td>
</tr>
<?php endforeach; ?>
</tbody>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><?php echo $sf_flash->get('messageFin')?></tr>
<?php endif; ?>
</table>

<?php if ($sf_user->hasCredential('troqueur')): ?>
   <?php echo link_to (image_tag('bt_ajouterCommunaute', array('border' => 0)), 'gereCommunaute/create?sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid'))?>
<?php endif; ?>


<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to('&laquo;', 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?page='.$pager->getFirstPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
  <?php echo link_to('&lt;', 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?page='.$pager->getPreviousPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?page='.$page.'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?> - <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('&gt;', 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?page='.$pager->getNextPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
  <?php echo link_to('&raquo;', 'gereCommunaute/'.$sf_request->getContext()->getActionName().'?page='.$pager->getLastPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid')) ?>
<?php endif ?>

