<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/01/06 21:56:25

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/trocabd',
), 'propel');
$this->databases['propel'] = $database;
