<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/01/06 21:57:15
$this->security = array (
  'show' => 
  array (
    'is_secure' => false,
  ),
  'showmap' => 
  array (
    'is_secure' => false,
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 'troqueur',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
