<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/01/06 22:00:41

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['sfStringValidator_recherche'] = new sfStringValidator();
  $validators['sfStringValidator_recherche']->initialize($context, array (
  'min' => 0,
  'min_error' => 'trop court',
  'max' => 200,
  'max_error' => 'critère trop long',
));
  $validatorManager->registerName('recherche', 0, 'Required', null, null, false);
  $validatorManager->registerValidator('recherche', $validators['sfStringValidator_recherche'], null);
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
  'param' => 
  array (
    'name' => 'formRecherche',
  ),
), 'symfony/filter');
}
