<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/01/06 22:00:41
$this->security = array (
  'list' => 
  array (
    'is_secure' => false,
  ),
  'recherche' => 
  array (
    'is_secure' => false,
  ),
  'mavitrine' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'troqueur',
        1 => 'manager',
      ),
    ),
  ),
  'savitrine' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'edit' => 
  array (
    'is_secure' => true,
    'credentials' => 'manager',
  ),
  'editserie' => 
  array (
    'is_secure' => true,
    'credentials' => 'manager',
  ),
  'editediteur' => 
  array (
    'is_secure' => true,
    'credentials' => 'manager',
  ),
  'editauteur' => 
  array (
    'is_secure' => true,
    'credentials' => 'manager',
  ),
  'showauteur' => 
  array (
    'is_secure' => false,
  ),
  'showediteur' => 
  array (
    'is_secure' => false,
  ),
  'showgenre' => 
  array (
    'is_secure' => false,
  ),
  'showserie' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
