<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Suppression de compte
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	

<?php echo form_tag('gereUtilisateur/erase', array('name' => 'formCompte')) ?>
<?php echo object_input_hidden_tag($user, 'getId') ?>
<table>
<tbody>
<?php include_partial('adresse', array('user' => $user)) ?>
<tr><td>Login:</td><td><?php echo $user->getLogin() ?></td></tr>
<tr><td>Mot de passe :</td><td><?php echo $user->getMdp() ?></td></tr>
<tr><td>Question :</td><td><?php echo $user->getQuestion() ?></td></tr>
<tr><td>Réponse :</td><td><?php echo $user->getReponse() ?></td></tr>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><td></td><td><?php echo $sf_flash->get('messageFin') ?></td></tr>
<?php endif; ?>
</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'Accueil/index') ?>
