<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Validation') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php if ($user->getId()): ?>
Modification d'utilisateur
<?php else: ?>
Inscription
<?php endif; ?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>	

<?php echo form_tag('gereUtilisateur/update', array('name' => 'formCompte')) ?>
<?php echo object_input_hidden_tag($user, 'getId') ?>
<table>
<tbody>
<tr><td><?php echo form_error('nom') ?></td></tr>
<tr><td>Nom :</td><td>		 <?php echo object_input_tag($user, 'getNom', array ('size' => 25,)) ?></td></tr>
<tr><td><?php echo form_error('prenom') ?></td></tr>
<tr><td>Prénom :</td><td>		 <?php echo object_input_tag($user, 'getPrenom', array ('size' => 25,)) ?></td></tr>
<tr><td><?php echo form_error('login') ?></td></tr>
<tr><td>Login :</td><td>		 <?php echo object_input_tag($user, 'getLogin', array ('size' => 15,)) ?></td></tr>
<tr><td><?php echo form_error('mdp') ?></td></tr>
<tr><td>Mot de passe :</td><td>		 <?php echo input_password_tag('mdp') ?></td></tr>
<tr><td>Re-saisissez le mot de passe pour vérification</td></tr>
<tr><td><?php echo form_error('mdp2') ?></td></tr>
<tr><td>Mot de passe :</td><td>		 <?php echo input_password_tag('mdp2') ?></td></tr>
<tr><td><?php echo form_error('rue2') ?></td></tr>
<tr><td>Adresse :</td><td>		 <?php echo object_input_tag($user, 'getRue2', array ('size' => 50,)) ?></td></tr>
<tr><td> </td><td>		 <?php echo object_input_tag($user, 'getRue3', array ('size' => 50,)) ?></td></tr>
<tr><td> </td><td>		 <?php echo object_input_tag($user, 'getRue4', array ('size' => 50,)) ?></td></tr>
<tr><td><?php echo form_error('cp') ?></td></tr>
<tr><td>Code postal :</td><td>		 <?php echo object_input_tag($user, 'getCp', array ('size' => 5,)) ?></td></tr>
<tr><td><?php echo form_error('ville') ?></td></tr>
<tr><td>Ville :</td><td>		 <?php echo object_input_tag($user, 'getVille', array ('size' => 50,)) ?></td></tr>
<tr><td><?php echo form_error('email') ?></td></tr>
<tr><td>Email :</td><td>		 <?php echo object_input_tag($user, 'getEmail', array ('size' => 50,)) ?></td></tr>
<tr><td>Saisissez une question et une réponse permettant de vous identifier</td></tr>
<tr><td><?php echo form_error('question') ?></td></tr>
<tr><td>Question :</td><td>		 <?php echo object_input_tag($user, 'getQuestion', array ('size' => 50,)) ?></td></tr>
<tr><td><?php echo form_error('reponse') ?></td></tr>
<tr><td>Réponse :</td><td>		 <?php echo object_input_tag($user, 'getReponse', array ('size' => 25,)) ?></td></tr>
</tbody>
</table>
<?php echo submit_image_tag('bt_valider', array('border' => 0)) ?>
  &nbsp;<?php echo link_to(image_tag('bt_abandonner', array('border' => 0)), 'accueil/index') ?>
