<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>

<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Liste des troqueurs 
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tr><td colspan="3">
<?php echo $pager->getNbResults() ?> résultats trouvés.<br/>
Affichage des résultats <?php echo $pager->getFirstIndice() ?> à  <?php echo $pager->getLastIndice() ?>.
</td></tr>
<thead class="listeObjetTitreTableau">
<tr>
  <th><?php echo link_to ('id', 'gereUtilisateur/listeTroqueurs?sortTroqueurs=id&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?></th>
  <th><?php echo link_to ('Login', 'gereUtilisateur/listeTroqueurs?sortTroqueurs=login&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?></th>
  <th><?php echo link_to ('Nom', 'gereUtilisateur/listeTroqueurs?sortTroqueurs=nom&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?></th>
  <th><?php echo link_to ('CP', 'gereUtilisateur/listeTroqueurs?sortTroqueurs=cp&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?></th>
  <th><?php echo link_to ('Ville', 'gereUtilisateur/listeTroqueurs?sortTroqueurs=ville&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?></th>
  <th><?php echo 'Lon' ?></th>
  <th><?php echo 'Lat' ?></th>
  <th><?php echo 'New Lon' ?></th>
  <th><?php echo 'New Lat' ?></th>
  <th>Action</th>
</tr>
</thead>
<tbody class="listeObjetLigneTableau">
<?php foreach ($pager->getResults() as $obj): ?>
<tr>
	  <td><?php echo $obj->getUserId() ?></td>
      <td><?php echo $obj->getLogin() ?></td>
      <td><?php echo $obj->getNom() ?></td>
      <td><?php echo $obj->getCp() ?></td>
      <td><?php echo $obj->getVille()  ?></td>
      <td><?php echo $obj->getLon() ?></td>
      <td><?php echo $obj->getLat() ?></td>
      <td><?php echo $obj->getRue2() ?></td>
      <td><?php echo $obj->getRue3() ?></td>
      <td><?php echo $obj->getReponse() ?></td>
      <td></td>
</tr>
<?php endforeach; ?>
<tr>
<?php echo $ex; ?>
</tr>
</tbody>
<?php echo '</BR>' ?>
<tr>
<td>
   <?php echo link_to ('Calculer lon&Lat', 'gereUtilisateur/calLonLat?sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
</td>
<td></td>
<td>
   <?php echo link_to ('MAJ trocabd', 'gereUtilisateur/majTroqueurs?sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
</td>
<td></td>
<td>
   <?php echo link_to ('Delete', 'gereUtilisateur/deleteTroqueursProd?sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
</td>
</tr>
</table>
<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to('&laquo;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getFirstPage().'&sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
  <?php echo link_to('&lt;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getPreviousPage().'&sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$page.'&sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?> - <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('&gt;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getNextPage().'&sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
  <?php echo link_to('&raquo;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getLastPage().'&sortTroqueurs='.$sf_request->getParameter('sortTroqueurs').'&filtreLonLat='.$sf_request->getParameter('filtreLonLat').'&envtroc='.$sf_request->getParameter('envtroc')) ?>
<?php endif ?>

