<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
<?php echo 'Liste des Troqueurs pour inviter à la communauté '.$sf_request->getParameter('communauteName')?>
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
<tr><td>
<?php echo $pager->getNbResults() ?> résultats trouvés.<br/>
Affichage des résultats <?php echo $pager->getFirstIndice() ?> à  <?php echo $pager->getLastIndice() ?>.
</td></tr>

<thead class="listeObjetTitreTableau">
<tr>
  <th></th>
  <th><?php echo link_to ('Créateur', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?sort=Login&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')) ?></th>
  <th>Action</th>
</tr>
</thead>
<tbody class="listeObjetLigneTableau">
<?php foreach ($pager->getResults() as $obj): ?>
<tr>
      <td><?php echo $obj->getLogin() ?></td>
      <td>
      <?php if(($sf_user->getAttribute('id')== $sf_request->getParameter('communautecreateurid')) ): ?>
		<?php $dansMaCommunaute = 'false'; ?>
	 	<?php foreach ($obj->getMembres() as $mem): ?>
	 			<?php if ($mem->getCommunauteId() == $sf_request->getParameter('communauteid')): ?>
	 				<?php $dansMaCommunaute = 'true' ?>
		      	<?php endif; ?>
	 	<?php endforeach; ?>
		<?php echo "<div id=\"btInviterCommunaute".$obj->getId()."\">" ?>
		<?php if($sf_user->hasCredential('troqueur')): ?>
			<?php if ($dansMaCommunaute=='false'): ?>
					<?php echo link_to_remote (image_tag('bt_InviterCommunaute', array('border' => 0)), array('update' => 'btInviterCommunaute'.$obj->getId() , 'url' => 'gereCommunaute/ajouterInvite?id='.$obj->getId().'&sort='.$sf_request->getParameter('sort').'&rechercher='.$rechercher.'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')))?>
			<?php else: ?>
					Déjà dans ma commmunauté
	      	<?php endif; ?>
      	<?php endif; ?>
		<?php echo "</div>" ?>
      <?php endif; ?>
</tr>
<?php endforeach; ?>
</tbody>
<?php if ($sf_flash->has('messageFin')): ?>
	<tr><?php echo $sf_flash->get('messageFin')?></tr>
<?php endif; ?>
</table>



<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to('&laquo;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getFirstPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')) ?>
  <?php echo link_to('&lt;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getPreviousPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')) ?>
  <?php $links = $pager->getLinks(); foreach ($links as $page): ?>
    <?php echo ($page == $pager->getPage()) ? $page : link_to($page, 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$page.'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')) ?>
    <?php if ($page != $pager->getCurrentMaxLink()): ?> - <?php endif ?>
  <?php endforeach ?>
  <?php echo link_to('&gt;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getNextPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')) ?>
  <?php echo link_to('&raquo;', 'gereUtilisateur/'.$sf_request->getContext()->getActionName().'?page='.$pager->getLastPage().'&sort='.$sf_request->getParameter('sort').'&utilid='.$sf_request->getParameter('utilid').'&communauteid='.$sf_request->getParameter('communauteid').'&communautecreateurid='.$sf_request->getParameter('communautecreateurid')) ?>
<?php endif ?>

