<?php use_helper('Javascript','GMap') ?>
<?php // use_helper('Javascript') ?>
<?php
// auto-generated by sfPropelCrud
// date: 2008/01/08 10:27:03
?>
<div class="roundedcornr_box_719771">
   <div class="roundedcornr_top_719771"><div></div></div>
      <div class="roundedcornr_content_719771">
Carte des troqueurs
      </div>
   <div class="roundedcornr_bottom_719771"><div></div></div>
</div>		

<table>
  <tr>
    <td valign="top" >
	<?php 
	if (($sf_request->getContext()->getModuleName()=="gereUtilisateur") and ($sf_request->getContext()->getActionName()=="showmap" ))
	{
 	 include_map($map,array('width'=>'400px','height'=>'250px')); 
	}
	 ?>
    </td>
  </tr>

</table>